name = "Dimers"                                                                                  
uuid = "a72a85d8-98b5-487d-943b-09dd1d5184ae"                                                                      
version = "0.1.0" 
